version: '3.1'
services: 
  discovery:
    image: sum-discovery:latest
    restart: always
    ports:
      - 8761:8761
    environment:
      SERVER_PORT: 8761 
  
  gateway:
    image: sum-gateway:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      EUREKA_URI: http://discovery:8761/eureka
  
  client:
    image: sum-client:latest
    restart: always
    #ports:
    #  - 9090:9090
    environment:
      SERVER_PORT: 9090
      EUREKA_URI: http://discovery:8761/eureka

  server:
    image: sum-server:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    #ports:
    #  - 9091:9091
    environment:
      SERVER_PORT: 9091
      EUREKA_URI: http://discovery:8761/eureka

  